-- ============================================================================
-- SCRIPT 13: Package + Trigger Monitor DDL
-- Scenario: audit operativo su CREATE/ALTER/DROP oggetti
-- ============================================================================

PROMPT ====================================================================
PROMPT  1. TABELLA LOG
PROMPT ====================================================================

CREATE TABLE dba_tools.ddl_audit_log (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_time      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  db_user         VARCHAR2(128),
  object_owner    VARCHAR2(128),
  object_name     VARCHAR2(128),
  object_type     VARCHAR2(64),
  event_name      VARCHAR2(64),
  sql_text        CLOB
);

PROMPT ====================================================================
PROMPT  2. PACKAGE MONITOR
PROMPT ====================================================================

CREATE OR REPLACE PACKAGE dba_tools.pkg_monit_ddl AS
  PROCEDURE log_event;
  PROCEDURE purge_old(p_days NUMBER DEFAULT 90);
END pkg_monit_ddl;
/

CREATE OR REPLACE PACKAGE BODY dba_tools.pkg_monit_ddl AS
  PROCEDURE log_event IS
    PRAGMA AUTONOMOUS_TRANSACTION;
    l_sql ORA_NAME_LIST_T;
    l_n   PLS_INTEGER;
    l_txt CLOB;
  BEGIN
    l_n := ora_sql_txt(l_sql);
    FOR i IN 1 .. l_n LOOP
      l_txt := l_txt || l_sql(i);
    END LOOP;

    INSERT INTO dba_tools.ddl_audit_log(
      db_user, object_owner, object_name, object_type, event_name, sql_text
    ) VALUES (
      SYS_CONTEXT('USERENV','SESSION_USER'),
      ORA_DICT_OBJ_OWNER,
      ORA_DICT_OBJ_NAME,
      ORA_DICT_OBJ_TYPE,
      ORA_SYSEVENT,
      l_txt
    );
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      ROLLBACK;
  END log_event;

  PROCEDURE purge_old(p_days NUMBER DEFAULT 90) IS
  BEGIN
    DELETE FROM dba_tools.ddl_audit_log
    WHERE event_time < SYSTIMESTAMP - NUMTODSINTERVAL(p_days, 'DAY');
    COMMIT;
  END purge_old;
END pkg_monit_ddl;
/

PROMPT ====================================================================
PROMPT  3. TRIGGER DATABASE
PROMPT ====================================================================

CREATE OR REPLACE TRIGGER dba_tools.trg_monit_ddl
AFTER DDL ON DATABASE
BEGIN
  dba_tools.pkg_monit_ddl.log_event;
END;
/

PROMPT ====================================================================
PROMPT  4. VALIDAZIONE
PROMPT ====================================================================

SELECT owner, trigger_name, status
FROM dba_triggers
WHERE trigger_name = 'TRG_MONIT_DDL';

SELECT event_time, db_user, object_owner, object_name, event_name
FROM dba_tools.ddl_audit_log
ORDER BY id DESC
FETCH FIRST 20 ROWS ONLY;

PROMPT ====================================================================
PROMPT  Fine Script 13 — Monitor DDL
PROMPT ====================================================================
