-- default tablespace for DBA_OP:

CREATE BIGFILE TABLESPACE DBA_OP_DATA DATAFILE SIZE 1024M AUTOEXTEND ON NEXT 128M MAXSIZE 32G LOGGING;


CREATE USER DBA_OP
  IDENTIFIED BY <password>
  DEFAULT TABLESPACE DBA_OP_DATA
  TEMPORARY TABLESPACE TEMPBIG
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 31 Roles for DBA_OP 
  GRANT CDB_DBA TO DBA_OP WITH ADMIN OPTION;
  GRANT DBA TO DBA_OP;
  GRANT EBAT_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT EBAT_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT EBA_API_PORTAL_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT EBA_API_PORTAL_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT EXP_FULL_DATABASE TO DBA_OP;
  GRANT FPADAUD_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADAUD_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADBFF_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADBFF_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADCNF_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADCNF_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADOPR_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADOPR_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADPRT_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADPRT_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADRPT_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADRPT_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADSTS_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPADSTS_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPAD_RSA_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPAD_RSA_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT FPAD_RSS_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT FPAD_RSS_RW TO DBA_OP WITH ADMIN OPTION;
  GRANT IMP_FULL_DATABASE TO DBA_OP;
  GRANT PDB_DBA TO DBA_OP WITH ADMIN OPTION;
  GRANT RESOURCE TO DBA_OP WITH ADMIN OPTION;
  GRANT SELECT_CATALOG_ROLE TO DBA_OP;
  GRANT TIPSEBAT_RO TO DBA_OP WITH ADMIN OPTION;
  GRANT TIPSEBAT_RW TO DBA_OP WITH ADMIN OPTION;
  ALTER USER DBA_OP DEFAULT ROLE ALL;
  -- 29 System Privileges for DBA_OP 
  GRANT ALTER ANY INDEX TO DBA_OP;
  GRANT ALTER ANY SEQUENCE TO DBA_OP;
  GRANT ALTER ANY TABLE TO DBA_OP;
  GRANT ALTER DATABASE TO DBA_OP;
  GRANT ALTER SESSION TO DBA_OP WITH ADMIN OPTION;
  GRANT ALTER SYSTEM TO DBA_OP;
  GRANT ALTER TABLESPACE TO DBA_OP;
  GRANT ALTER USER TO DBA_OP WITH ADMIN OPTION;
  GRANT CREATE ANY INDEX TO DBA_OP;
  GRANT CREATE ANY SEQUENCE TO DBA_OP;
  GRANT CREATE ANY TABLE TO DBA_OP;
  GRANT CREATE ROLE TO DBA_OP;
  GRANT CREATE SESSION TO DBA_OP WITH ADMIN OPTION;
  GRANT CREATE SYNONYM TO DBA_OP WITH ADMIN OPTION;
  GRANT CREATE TABLESPACE TO DBA_OP;
  GRANT CREATE TYPE TO DBA_OP;
  GRANT CREATE USER TO DBA_OP;
  GRANT DELETE ANY TABLE TO DBA_OP;
  GRANT DROP ANY INDEX TO DBA_OP;
  GRANT DROP ANY TABLE TO DBA_OP;
  GRANT EXECUTE ANY PROCEDURE TO DBA_OP;
  GRANT GRANT ANY PRIVILEGE TO DBA_OP;
  GRANT INSERT ANY TABLE TO DBA_OP;
  GRANT LOCK ANY TABLE TO DBA_OP;
  GRANT PURGE DBA_RECYCLEBIN TO DBA_OP;
  GRANT SELECT ANY DICTIONARY TO DBA_OP;
  GRANT SELECT ANY TABLE TO DBA_OP;
  GRANT UNLIMITED TABLESPACE TO DBA_OP WITH ADMIN OPTION;
  GRANT UPDATE ANY TABLE TO DBA_OP;
  -- 1 Tablespace Quota for DBA_OP 
  ALTER USER DBA_OP QUOTA UNLIMITED ON DBA_OP_DATA;
  -- 11 Object Privileges for DBA_OP 
    GRANT SELECT ON SYS.DBA_DATA_FILES TO DBA_OP;
    GRANT SELECT ON SYS.DBA_FREE_SPACE TO DBA_OP;
    GRANT SELECT ON SYS.DBA_RECYCLEBIN TO DBA_OP;
    GRANT SELECT ON SYS.DBA_TABLESPACES TO DBA_OP;
    GRANT SELECT ON SYS.DBA_USERS TO DBA_OP;
    GRANT EXECUTE ON SYS.DBMS_LOCK TO DBA_OP;
    GRANT EXECUTE ON SYS.DBMS_RANDOM TO DBA_OP;
    GRANT EXECUTE ON SYS.DBMS_SYSTEM TO DBA_OP;
    GRANT EXECUTE ON SYS.UTL_FILE TO DBA_OP;
    GRANT EXECUTE ON SYS.UTL_SMTP TO DBA_OP;
    GRANT EXECUTE ON SYS.UTL_TCP TO DBA_OP;
