-- Source: https://www.scriptdba.com/architettura-multitenant-database-oracle/
-- Title: Architettura Multitenant Database Oracle

CREATE PLUGGABLE DATABASE pdb1;

CREATE PLUGGABLE DATABASE pdb1;

ALTER SESSION SET CONTAINER=pdb1;

ALTER SESSION SET CONTAINER=pdb1;

ALTER PLUGGABLE DATABASE PDB1 OPEN;

ALTER PLUGGABLE DATABASE PDB1 OPEN;

CREATE USER PIPPO IDENTIFIED BY xxx;

CREATE USER PIPPO IDENTIFIED BY xxx;

CREATE USER C##PIPPO IDENTIFIED BY xxx all;

CREATE USER C##PIPPO IDENTIFIED BY xxx all;

AlTER SESSION SET CONTAINER=pdb1;

AlTER SESSION SET CONTAINER=pdb1;

ATER SESSION SET CONTAINER=cdb$root;

ATER SESSION SET CONTAINER=cdb$root;

conn sys/xxx@pdb1 as sysdba;

conn sys/xxx@pdb1 as sysdba;

export ORACLE_PDB_SID=PDB1;

export ORACLE_PDB_SID=PDB1;

sqlplus / as sysdba;

sqlplus / as sysdba;

show con_name;

show con_name;

select name from V$CONTAINERS;

select name from V$CONTAINERS;

select pdb_name, status from DBA_PDBS order by 1;

select pdb_name, status from DBA_PDBS order by 1;

ALTER PLUGGABLE DATABASE pdb1 OPEN;
ALTER PLUGGABLE DATABASE pdb1 SAVE STATE;

ALTER PLUGGABLE DATABASE pdb1 OPEN;
ALTER PLUGGABLE DATABASE pdb1 SAVE STATE;

DROP PLUGGABLE DATABASE pdb1 INCLUDING DATAFILES;

DROP PLUGGABLE DATABASE pdb1 INCLUDING DATAFILES;

GRANT CREATE TABLESPACE TO PIPPO;
GRANT CONNECT TO PIPPO;
GRANT CREATE TABLE TO PIPPO;
GRANT CREATE ANY DIRECTORY TO PIPPO;

GRANT CREATE TABLESPACE TO PIPPO;
GRANT CONNECT TO PIPPO;
GRANT CREATE TABLE TO PIPPO;
GRANT CREATE ANY DIRECTORY TO PIPPO;

